name: CI/CD - GitHub Pages

on:
  push:
    branches: [main]

jobs:
  first-deploy:
    name: Desplegar en GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}"