name: "Deploy Codigo Facilito"

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: "Primer Job"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hello", "World", "Bootcamp Codigo Facilito"]
    
    steps:
      - name: Print message
        run: echo ${{ matrix.message }}        
