name: "Deploy Codigo Facilito"

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: "Primer Job"
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: production

    steps:
      - name: Working directory
        run: ls -al
      
      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: ls -al
  
  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo 2 ${{ github.ref }}"
